
export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED', // Waiting for doc review
  DOCS_APPROVED = 'DOCS_APPROVED', // Passed docs, pending interview fee
  DOCS_REJECTED = 'DOCS_REJECTED', // Needs re-upload
  INTERVIEW_READY = 'INTERVIEW_READY', // Fee paid, ready to book slot
  INTERVIEW_BOOKED = 'INTERVIEW_BOOKED',
  PASSED = 'PASSED', // Passed interview, pending tuition fee
  ENROLLED = 'ENROLLED', // Paid tuition, officially a student
  FAILED = 'FAILED'
}

export enum DocumentStatus {
  PENDING = 'pending',
  UPLOADED = 'uploaded',
  APPROVED = 'approved',
  REJECTED = 'rejected'
}

export enum Gender {
  MALE = 'Male',
  FEMALE = 'Female',
  OTHER = 'Other'
}

export type FeeStatus = 'PENDING' | 'PAID' | 'REJECTED';

export interface DocumentItem {
  id: string;
  name: string;
  status: DocumentStatus;
  reviewNote?: string;
  fileUrl?: string; // Mock URL
  fileName?: string; // Display name of uploaded file
  isDynamic?: boolean; // Flag to identify docs generated by education level
  configId?: string; // Link to DocumentConfig
  uploadedBy?: 'applicant' | 'admin';
}

export interface DocumentConfig {
  id: string;
  label: string;
  isStandard: boolean; // true if it cannot be deleted
  isHidden: boolean;
  order: number;
}

// --- Custom Form Fields ---
export type CustomFieldType = 'text' | 'dropdown' | 'checkbox' | 'radio' | 'score';

export interface CustomFieldDefinition {
  id: string;
  label: string;
  type: CustomFieldType;
  options?: string[]; // For dropdowns, radio, checkbox groups, or Exam Names for 'score' type
  required?: boolean;
  minScore?: number;
  maxScore?: number;
  description?: string; // Help text
  scoreConfig?: { exam: string, min: number, max: number }[];
  allowNoScore?: boolean;
  itemCount?: number; // Number of items for list inputs (e.g. Recommendations)
}

// New Interface for managing Layout (Order & Visibility)
export interface FieldConfig {
  id: string; // matches Applicant keys (fullName, age) or custom field IDs
  label: string;
  type: CustomFieldType | 'standard'; // 'standard' for hardcoded fields
  options?: string[];
  isStandard: boolean; // true if it cannot be deleted (only hidden)
  isHidden: boolean;
  order: number;
  minScore?: number;
  maxScore?: number;
  description?: string;
  scoreConfig?: { exam: string, min: number, max: number }[];
  allowNoScore?: boolean;
  itemCount?: number;
}

// --- Interview Management ---
export type InterviewType = 'Onsite' | 'Online';

export interface InterviewGroup {
  id: string;
  name: string;
  applicantIds: string[]; // Ordered list of Applicant IDs
}

export interface InterviewSlot {
  id: string;
  dateTime: string; // ISO Date String
  endTime: string; // ISO Date String
  location: string; // Room number or Zoom Link
  type: InterviewType;
  capacity: number;
  booked: number;
  groups?: InterviewGroup[];
}

// --- Payment Configuration ---
export interface PaymentConfig {
  kplus: boolean;
  qrcode: boolean;
  requireApplicationFee?: boolean;
  requireInterviewFee?: boolean;
  requireTuitionFee?: boolean;
}

export interface EducationRecord {
  id: string;
  level: string; // e.g. "Bachelor's Degree"
  degreeName?: string; // e.g. "B.Sc. Computer Science"
  institution?: string; // e.g. "Chulalongkorn University"
  gpax: string;
  fieldOfStudy?: string;
  startYear?: string;
  endYear?: string;
}

export interface Applicant {
  id: string;
  fullName: string;
  age: number;
  gender: Gender;
  email: string;
  phone: string;
  address: string;
  birthDate?: string;
  educations: EducationRecord[]; // Changed to array of objects
  status: ApplicationStatus;
  documents: Record<string, DocumentItem>;
  
  interviewSlotId?: string; // ID reference to InterviewSlot
  interviewSlot?: string; // Legacy support / Display string
  
  // Store answers persistently: { questionId: answerValue }
  examAnswers?: Record<string, string | string[]>; 
  examScore?: number; // Automated online exam score (if any)
  
  // Manual Evaluation Scores
  writtenScore?: number; // Offline test score entered by admin
  interviewScore?: number; // Interview score entered by admin
  
  evaluation?: {
    score: number; // Total or final score
    comment: string;
  };
  // Store dynamic field data
  customData?: Record<string, any>;
  
  // E-Signature
  isESigned?: boolean;
  eSignTimestamp?: string;
  signatureImage?: string; // Base64 image

  // Admin Review Data
  feeStatuses?: {
      application: FeeStatus;
      interview: FeeStatus;
      tuition: FeeStatus;
  };
  fieldRejections?: Record<string, string>; // fieldId -> Rejection Reason
  examGrading?: Record<string, number>; // questionId -> Score given by admin

  // Management
  isStarred?: boolean;
  rankingScore?: number; // 1-10 Score for internal ranking
  lastNotifiedStatus?: ApplicationStatus; // Status visible to user (syncs only when admin publishes)
}

export enum QuestionType {
  MCQ_SINGLE = 'MCQ_SINGLE',
  MCQ_MULTI = 'MCQ_MULTI',
  ESSAY = 'ESSAY'
}

export interface QuestionOption {
  id: string;
  text: string;
  isCorrect: boolean;
  allowInput?: boolean;
}

export interface ExamQuestion {
  id: string;
  suiteId: string; // Link to a specific test suite (e.g., Aptitude, Attitude)
  text: string;
  type: QuestionType;
  score: number;
  options?: QuestionOption[];
  isGraded?: boolean;
}

export interface ExamSuite {
  id: string;
  title: string;
  description: string;
}

export interface StaffStats {
  total: number;
  pendingReview: number;
  interviewReady: number;
  passed: number;
}
